id: adsb
name: ADSB Plugin
version: "0.9.0"
entry_point: plugin/adsb.py
class_name: ADSBPlugin
description: "Get aircraft data from ADSB aggregators"
icon: "fas fa-plane"
author: Stefan Gofferje
plugin_type: gps
tier: community
min_trakbridge_version: "2.0.0"
